const data= {
    products: [
        {
            _id: '1',
            name:'nike slim shirt',
            category:'shirts',
            image:'/images/p1.jpg',
            price:120,
            brand:'nike',
            ratings: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name:'adidas slim shirt',
            category:'shirts',
            image:'/images/p2.jpg',
            price:100,
            brand:'addidas',
            ratings: 4.0,
            numReviews: 13,
            description: 'high quality product',
        },
        {
            _id: '3',
            name:'nike  shirt',
            category:'shirts',
            image:'/images/p3.jpg',
            price:125,
            brand:'nike',
            ratings: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            _id: '4',
            name:' slim shirt',
            category:'shirts',
            image:'/images/p4.jpg',
            price:150,
            brand:'h and m',
            ratings: 4.7,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '5',
            name:'gucci slim shirt',
            category:'shirts',
            image:'/images/p5.jpg',
            price:1200,
            brand:'gucci',
            ratings: 3.0,
            numReviews: 20,
            description: 'high quality product',
        },
        {
            _id: '6',
            name:'LV slim shirt',
            category:'shirts',
            image:'/images/p6.jpg',
            price:12000,
            brand:'LV',
            ratings: 4.9,
            numReviews: 10,
            description: 'high quality product',
        },
    ]
}

export default data;